messages:

  ConsoleSender: "You not player"
  reloadConfigs: "&7[&6TK&7] &aУспешно перезагрузил конфиг."
  help:
    - "&6ToffiKnockback:"
    - "&7 * &6/kb help &7- команда что-бы узнать информацию."
    - "&7 * &6/kb &7- команда для вкл/выкл силового поля."
    - "&7 * &6/kb list&7- команда что-бы посмотреть список друзей которые могут зайти в ваше поле."
    - "&7 * &6/kb add (ник)&7- команда добавления игрока в список друзей."
    - "&7 * &6/kb remove (ник)&7- команда удаления игрока из списка друзей."
  noPerm: "&7[&6TK&7] &cУ вас нет прав"
  start: "&7[&6TK&7] &7Вы &aвключили&7 силовое поле, которое отталкивает игроков от вас."
  stop: "&7[&6TK&7] &7Вы &cотключили&7 силовое поле, которое отталкивало игроков от вас."
  bypass: "&7[&6TK&7] &7У игрока &6{player}&7 есть имуннитет от силового поля."
  noLimit: "&7[&6TK&7] &7Вы достигли лимит у вас 5 из 5 друзей."
  wl-alredy: "&7[&6TK&7] &6{player}&7 уже в списке ваших друзей."
  wl-notPlayer: "&7[&6TK&7] &6{player}&7 нету в списке друзей."
  wl-add: "&7[&6TK&7] &7Вы добавили в список друзей игрока &6{player}"
  wl-remove: "&7[&6TK&7] &7Вы удалили из списка друзей игрока &6{player}"
  wl-null: "&7[&6TK&7] &7У вас в списке друзей нету игроков."
  notPlayer: "&7[&6TK&7] &6{target}&7 нет на сервере"
  friends-name: "&7[&6TK&7] &7Ваши друзья &6{friends-size}&7/&65&7:" # Настройка отоброжения сообщение при команде /kb list
  list: "&7 * &6{friends}" #отоброжения списка друзей игрока команды /kb list
  youNot: "&7[&6TK&7] &cНельзя добавить самого себя в вайт-лист"
  distaneNot: "&7[&6TK&7] &7Отойдите чуть назад у игрока &6{player}&7 включено силовое поле."




settings-kb:
  opDistance: 5
  maxLimitFriends: 5 #Лимит сколько игрок может добавлять друзей в свой список исключения
  yBase: "0.8" #Минимально кол-во блоков как откинит игрока
  yMax: "10.0" #Максимальное кол-во блоков


mysql:
  ip: "193.168.131.40"
  port: 3306
  username: "a0657437_test"
  password: "LOSWm9ec"
  database: "a0657437_test"
  table: "toffiknockback"

perms:
  kb-reload: "ToffiKnockback.reload" #право на перезагрузку конфигов, а именно на команду /kb reload
  kb-cmd: "ToffiKnockback.use" #право на включение/выключения поля
  kb-usecmd: "ToffiKnockback.usecmd" #право на команду /kb add/remove/help
  kb-bypass: "ToffiKnockback.bypass" #право что-бы игрок не отталкивался от поля
  kb-limit: "ToffiKnockback.limit." #лимит поля для игрока, в конце точку НЕ убирать
